name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        python -m build

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: WhatMail ${{ github.ref }}
        body: |
          ## What's Changed
          - See CHANGELOG.md for detailed changes

          ## Installation
          ```bash
          pip install whatmail
          ```

          ## Documentation
          - [README](https://github.com/yourusername/whatmail/blob/main/README.md)
          - [Documentation](https://github.com/yourusername/whatmail/blob/main/WhatMail-Project-Documentation.md)

        draft: false
        prerelease: false
